apiVersion: v1
kind: Pod
metadata:
  labels:
    app: iperf3-client
  name: iperf3-client
spec:
  containers:
  - name: iperf
    image: infrabuilder/bench-iperf3
    args:
    - /bin/sh
    - -c
    - sleep 30000
  # nodeSelector:
  #   kubernetes.io/hostname: $CLIENT_NODE
  restartPolicy: Never