apiVersion: v1
kind: Pod
metadata:
  labels:
    app: netperf-server
  name: netperf-server
spec:
  containers:
  - name: netperf
    image: networkstatic/netserver
    args:
    - netserver
    - -D
  # nodeSelector:
  #   kubernetes.io/hostname: $SERVER_NODE
---
apiVersion: v1
kind: Service
metadata:
  name: netperf-server
spec:
  selector:
    app: netperf-server
  ports:
    - protocol: TCP
      port: 12865
      targetPort: 12865
      name: tcp
    - protocol: UDP
      port: 12865
      targetPort: 12865
      name: udp